modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/catter1/Stardust_Remove_Intro_Message/issues"

[[mods]]
    modId="remove_sdl_intro"
    version="1.2.2"
    displayName="Remove Stardust Labs Intro Message"
    displayURL="https://github.com/catter1/Stardust_Remove_Intro_Message"
    logoFile="pack.png"
    authors="catter1"
    description="Removes the intro message that appears with Stardust Labs projects."

[[dependencies.remove_sdl_intro]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"